# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines-new
pool: ofqual-agent
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
      - checkout: self
- stage: Dockerize
  displayName: Dockerize Stage
  jobs:
    - job: DockerizeJob
      displayName: Dockerize Job
        # pool:
        #   vmImage: 'windows-2019'
      steps:
        - checkout: self  #      
        - task: Docker@2
          displayName: Build an image
          inputs:
            command: build
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: |
              $(tag)
